[script]
name = "Netmarble Launcher"
description = "Downloads the official Netmarble Launcher installer and runs it in a prefix of your choice"
author = "reakjra"
note = "Download might take a bit.\nLet the launcher open when the installer finishes, then close it so the script can continue. Closing the installer early can leave the install folder unrecorded."
icon = "./icon.png"

[[input]]
id = "prefix"
kind = "prefix"
picker = "path"
label = "Wine prefix"

[[input]]
id = "runner"
kind = "runner"
label = "Runner (any Proton works~)"

[[step]]
task = "init_prefix"

[[step]]
task = "download"
url = "https://apis.netmarble.com/cpplauncher/view/launcher/download"
dest = "${cache}/Netmarble_Launcher_Setup.exe"

[[step]]
task = "run_exe"
exe = "${cache}/Netmarble_Launcher_Setup.exe"
dll_overrides = { "powershell.exe" = "d" }

[game]
name = "Netmarble Launcher"
exe_from_registry = "ebab0fa0-3e67-5055-898a-0b6ee5815a99"
exe = "Netmarble Launcher.exe"

[game.dll_overrides]
"powershell.exe" = "d"
